### ISSUE TITLE
Timer that triggers at start of duration instead of at end

### ISSUE THREAD

**Issue by dpetican** [EasyG0ing1/BlockNot#14]
I feel this must be simple but...  I often want to sample something like battery voltage every x minutes and also want to sample the voltage at the start of the program.  I could do this in several ways including:

1. Sample voltage in setup() then sample every x minutes in the loop() using a timer.
2. Use a boolean that is initialized to true, then set to false after the first sample.  Something like:
```
BlockNot timer(360000);
bool firstSample = true;
if (firstSample || timer.TRIGGERED) {
  firstSample = false;
  ...
}
```
Is there a construction similar to the second example that will work without the boolean?  I feel it would be much cleaner code.  Thanks for updating the code into separate files.

**Comment by EasyG0ing1** [comment]
Hi @dpetican ...

I think the way I would handle this... since this duration of your timer is so long ... would be to take a reading in the setup() method, then in the last line of setup, do a reset of the timer that way when the loop starts, you have your initial reading with the next reading coming down at a time that is precisely equal to the duration of the timer.

```
BlockNot batteryTimer(120, SECONDS);
long voltage = 0;
int batPin = 9;

readBatteryVoltage() {
  voltage = analogRead(batPin);
}

setup() {
  Serial.being(9600);
  PinMode(batPin, INPUT);
  //etc. etc.
  readBatteryVoltage();
  batteryTimer.RESET;
}

loop() {

  if(batteryTimer.TRIGGERED) {
    readBatteryVoltage();
  }

}
```

Also keep in mind that when the Arduino is running loop or executing any code for that matter, it only consumes a couple of MICRO SECONDS to execute a command... so in this scenario, the time between the RESET command in the setup method and the time to when the loop tests for the TRIGGER of the timer ... there might be one or two microseconds that pass between those two commands.  This means that the Arduino basically runs a complete loop cycle in upwards of almost 1 MILLION times per second ... this would then mean that the test for the TRIGGER of the timer will actually happen about a million times per second ... so it becomes a moot point to be concerned with any time delays between the execution of commands within the code unless those commands perform blocking activities to where the code run pointer isn't given back to the microcontroller until that blocking code is done executing.

**Comment by EasyG0ing1** [comment]
@dpetican 

Hello, I forgot this issue was open ... and after re-reading it, I want to show you how I write my code for these things that makes the code much easier to read and write. The button debounce is just peppered in to show another example of a different use case for BlockNot.

```C++
BlockNot showVoltageTimer(120, SECONDS);
BlockNot buttonDebounce(500);

#define batPin 9
#define button 10

#define READ_BATTERY analogRead(batPin)
#define BUTTON_PRESSED digitalRead(button) == LOW

bool toggleSomeState = false;

String calcVoltage(unsigned long pinValue) {
    static const double factor = 5.0 / 1024;  // Arduino with 5 volt internal reference
    double volts = (double) (pinValue * factor);
    return String(volts, 2) + "V";            // Voltage with 2 decimal precision (ex: 2.34V)
}

void showVoltage() {
    Serial.println(calcVoltage(READ_BATTERY));
}

setup() {
    Serial.being(9600);
    pinMode(batPin, INPUT);
    pinMode(battery, INPUT_PULLUP);
    showVoltage();
    showVoltageTimer.RESET;
}

loop() {
    if(showVoltageTimer.TRIGGERED)
        showVoltage();

    if(BUTTON_PRESSED)
        if(buttonDebounce.TRIGGERED)
            toggleSomeState = !toggleSomeState;
}
```

I think in terms of C++, the readability of that code is about as good as it gets. I think even a non-programmer could read the loop and understand what the code is doing. And that is always what I strive for ... I strive for the loop to be the "story teller" of what the program does, while masking all of the ugly parts of the code using macros and terms that are clear and easy to follow.

**Comment by dpetican** [comment]
I've been using the .RESET macro in setup since you first showed that to me.  Its good enough for most use cases.  Although semantically it would be better to initialize a timer without having to start it (ie disabled).  Then at the end of setup or elsewhere just enable/start it.

I tried initializing a timer with zero seconds thinking that would create a disabled timer but that didn't seem to work.  In some cases I want to test for something like first trigger before I ever start the timer.  In that case I have to disable the timer in setup and then also check for first trigger AND timer enabled.   But I know enough now that I can just play around and make the library do what I want.

BTW, this is one of my goto libraries for almost every project except for small ATTiny projects.  Along with ArduinoJson it makes life so much easier.  Thanks.

**Comment by EasyG0ing1** [comment]
> I've been using the .RESET macro in setup since you first showed that to me. Its good enough for most use cases. Although semantically it would be better to initialize a timer without having to start it (ie disabled). Then at the end of setup or elsewhere just enable/start it.
> 
> I tried initializing a timer with zero seconds thinking that would create a disabled timer but that didn't seem to work. In some cases I want to test for something like first trigger before I ever start the timer. In that case I have to disable the timer in setup and then also check for first trigger AND timer enabled. But I know enough now that I can just play around and make the library do what I want.
> 
> BTW, this is one of my goto libraries for almost every project except for small ATTiny projects. Along with ArduinoJson it makes life so much easier. Thanks.

I like your suggestions about being able to instantiate a timer that is stopped. The idea never crossed my mind because I've never had a need to do that, but I can see the value in being able to do it. I'm going to work on adding that constructor to the library. I'm also going to be adding the ability to dictate which units a developer can use when calling the .setDuration() method. Based on some email correspondence, I've discovered that it seems people assume that the units can be specified inside the arguments of the method. And of course, that makes sense to me, so I will make it so.

And that's a great compliment about being your goto library. I appreciate that feedback ... makes the effort all worthwhile ☺

Mike

**Comment by EasyG0ing1** [comment]
@dpetican - I updated the library - current version is 2.0.6 and it should be available in the Arduino IDE within an hour.

I added new constructors that allow you to create a timer in a STOPPED state. Look at the Constructor definitions in BlockNot.h to see where you can pass the option to create a stopped timer in any given constructor argument. Simply using the word STOPPED will achieve what you want. 

You should also read the top of [this section](https://github.com/EasyG0ing1/BlockNot#start--stop) in the README because that will directly apply to your use case in this context. 

Let me know if it works as expected. I didn't have time to test it, but I did compile the library and it compiled fine so I know there are no errors in it ... but I didn't have time to test the logic though it's fairly simple enough and it looks right to me.
